help([[
Load environment for running the GDAS application with Intel compilers and MPI.
]])

local pkgName    = myModuleName()
local pkgVersion = myModuleVersion()
local pkgNameVer = myModuleFullName()

prepend_path("MODULEPATH", '/opt/spack-stack/spack-stack-1.8.0/envs/unified-env/install/modulefiles/Core')
--prepend_path("MODULEPATH", '/scratch1/NCEPDEV/da/python/opt/modulefiles/stack')

-- below two lines get us access to the spack-stack modules
load("stack-intel")
load("stack-intel-oneapi-mpi")
-- JCSDA has 'jedi-fv3-env/unified-dev', but we should load these manually as needed
load("cmake")
load("gettext")
--load("libunistring/1.1")
--load("libidn2")
--load("pcre2")
load("curl")
--load("zlib")
load("git")
--load("pkg-config")
load("hdf5")
load("parallel-netcdf")
load("netcdf-c")
load("nccmp")
load("netcdf-fortran")
load("nco")
load("parallelio")
load("wget")
load("boost")
load("bufr")
load("git-lfs")
load("ecbuild")
load("openjpeg")
load("eccodes")
load("eigen")
load("openblas")
load("eckit")
load("fftw")
load("fckit")
load("fiat")
--load("ectrans")
load("fms")
load("atlas")
load("sp")
load("gsl-lite")
load("libjpeg")
load("krb5")
load("libtirpc")
load("hdf")
load("jedi-cmake")
load("libpng")
load("libxt")
load("libxmu")
load("libxpm")
load("libxaw")
load("udunits")
load("ncview")
load("netcdf-cxx4")
load("json")
--load("crtm/v2.4_jedi")
--load("rocoto")
load("prod_util")

load("py-jinja2")
load("py-netcdf4")
load("py-pybind11")
load("py-pycodestyle")
load("py-pyyaml")
load("py-scipy")
load("py-xarray")
load("py-f90nml")
load("py-pip")
load("py-click")

setenv("CC","mpiicc")
setenv("FC","mpiifort")
setenv("CXX","mpiicpc")

local mpiexec = 'mpiexec'
local mpinproc = '-n'
setenv('MPIEXEC_EXEC', mpiexec)
setenv('MPIEXEC_NPROC', mpinproc)

setenv("CRTM_FIX","/scratch1/NCEPDEV/da/role.jedipara/GDASApp/fix")
setenv("GDASAPP_TESTDATA","/scratch1/NCEPDEV/da/role.jedipara/GDASApp")
setenv("GDASAPP_UNIT_TEST_DATA_PATH", "/scratch1/NCEPDEV/da/role.jedipara/GDASApp/unittestdata")
--prepend_path("PATH","/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/prod_util/1.2.2/bin")

whatis("Name: ".. pkgName)
--whatis("Version: ".. pkgVersion)
whatis("Category: GDASApp")
whatis("Description: Load all libraries needed for GDASApp")
